{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-metrics
  labels:
    app: {{ template "polyaxon.fullname" . }}-metrics
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.metrics }}
    role: {{ .Values.roles.log }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-metrics
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.metrics }}
    app.kubernetes.io/component: {{ .Values.roles.log }}
    app.kubernetes.io/managed-by: "helm"
{{- if .Values.metrics.service.labels }}
{{ toYaml .Values.metrics.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - port: 9102
    targetPort: 9102
    protocol: TCP
    name: metrics
  - port: 9125
    targetPort: 9125
    protocol: UDP
    name: statsd
  selector:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-metrics
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
